version: 2
jobs:
  server:
    docker:
      - image: circleci/node:8.15.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "Testing the server..."
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
  client:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm

    working_directory: ~/repo
    steps:
      - checkout
      - run: 'node -v'
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run: yarn install --frozen-lockfile --ignore-engines

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!

      - run: yarn start & sleep 2

      - run: yarn --cwd ~/repo/client install --frozen-lockfile --ignore-engines

      - run: yarn --cwd ~/repo/client start & sleep 20

      - run: yarn cy:run
workflows:
  version: 2
  server_client:
    jobs:
      - server
