version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - run: yarn install
      - run: CI=true yarn start
  test:
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - run: echo "Running server tests..."
      - run: yarn install
      - run: yarn test
workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - test
